### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by Gamer2020** [Spitz3492/PokeMMO-Bot#1]
Hi. Just tried this out but wasn't sure exactly how to use it. It look like you enter your pokemon + attacks then click begin but it didn't do anything. Do you have any basic instructions? Is this currently working?

**Comment by Spitz3492** [comment]
I haven't looked at this project in awhile. Bare in mind this project is not finished. It's only features are detecting when in battle and automatically clicking your Pokemon's most powerful move. It has yet to recognize PP and I haven't integrated my PokeNeuro neural network into this tool yet to recognize enemies and friendly Pokemon. You first enter your Pokemon name then press load and fill in their attacks. Then press add to add the Pokemon to your party. Then once every Pokemon in your party is added, press save. Then select the Pokemon in your party which is fighting, and press begin. I would use this as a rough guide to make your own.

**Comment by Gamer2020** [comment]
That's what I was trying to do but it doesn't seem to be working. Maybe this isn't working anymore as it has been a while. Thank you for answering!

https://i.imgur.com/VacFXOO.png
